### PR TITLE
feat: autodeploy workflow added

### PR DESCRIPTION
**Pull request by vimode**
Hey,

As per our discussion in #220 I have setup the workflow, tested it and it works. 🎉
You can check the successful [action run log here](https://github.com/vimode/portfolio-ideas/actions/runs/3995636766/jobs/6854738185) 🔍
And the updated [`portfolio.md` from the successful](https://github.com/vimode/portfolio-ideas/blob/workflow/autodeploy/docs/portfolio.md) action run. 

As of now for the test, its limited to pushes to this branch.
But what do you think will be better? Run the action to pushes only to `main` branch so only when you merge it to `main` or make it so that for all the pushes? 
The second option has the advantage for the contributor to see the preview build too!

Let me know if the workflow looks good; the name of the workflow, the commit message and all the steps.
I will make the necessary changes and fix the README to remove the test content once everything looks good to you. 

_If you want to test it once again in this repo before merging in the `main`, make a new branch and merge this into it or I can make a new PR to merge into that new branch to test._

Thank you.

### CODE REVIEW

**Comment by vimode** [comment]
Oh! The Vercel preview shows the test deployment too! 😃

**Review by Evavic44 — CHANGES_REQUESTED** [review]
This is awesome! Nice work, @vimode 💯

## Update
For the branch, we'll go with `main`. Since we have Vercel preview mode, we can see the changes without having to test it on a separate branch.

The workflow is splendid! Just change the commit message to 'docs: deploy site' so it can be easy to track on the changelog.

Nice work once again. 👍🏽

**Comment by vimode** [comment]
I certainly learned a lot from this process so thank you @Evavic44 

I had to update the steps a bit as escaping characters in yaml with github actions proved to be a different challenge. 😆
Updated it to run for `main` branch pushes only and fixed the README.

**Review by Evavic44 — APPROVED** [review]
Likewise. Thanks for the contribution. 
@all-contributors please add @vimode for code and doc

**Comment by vimode** [comment]
Hey @Evavic44 

Just a heads-up, 
[GitHub Actions – Updating the default GITHUB_TOKEN permissions to read-only](https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/)

The post says we can still flip its permissions, which we have done here 
https://github.com/Evavic44/portfolio-ideas/blob/40c49e99e73eb06bd1cfbf3680feba89cdd130e7/.github/workflows/autodeploy.yml#L9-L10
But just something to watch out for on the next action run.

**Comment by Evavic44** [comment]
> 

That's good to know, thanks for the heads up. 💯

**Pull request merged**
