### PR TITLE
Add Tanuj Chakraborty

### PR DESCRIPTION
**Pull request by i-am-tj**
### Portfolio Author

[@i-am-tj](https://github.com/i-am-tj)

### Portfolio Link?

https://www.iamtj.dev/

### GitHub Link:

https://github.com/i-am-tj/iamtj.dev

### Tech Stack

Next.js, TypeScript, Tailwind CSS

### CODE REVIEW

**Review by israelmitolu — CHANGES_REQUESTED** [review]
Hi @i-am-tj 
Kindly follow the guidelines here on how to add your portfolio to the repo: https://portfolio-ideas.vercel.app/guide.html#step-3-add-portfolio-details
So, instead of uploading your screenshot as a file in the main branch, just drag and drop into the Readme. 

Also, before you do that, kindly compress it using [compressnow](https://compressnow.com/) or [tinypng](https://tinypng.com/). We have many images in the repo, so we try to keep them as small as possible. Ideally less than 150kB.

Thanks for understanding :)

**Comment by i-am-tj** [comment]
Hi @israelmitolu 
I have done the requested changes.
Please let me know if it's fine now. 
Thanks :)

**Review by israelmitolu — APPROVED** [review]
LGTM

**Comment by israelmitolu** [comment]
> Hi @israelmitolu I have done the requested changes. Please let me know if it's fine now. Thanks :)

Yes, it is. Thank you!

**Pull request merged**
