### PR TITLE
Add Sachin Chaurasiya Portfolio

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
### Portfolio Author

Sachin Chaurasiya

### Portfolio Link?

https://sachinchaurasiya.dev

### GitHub Link:

None

### Tech Stack

HTML, CSS, JavaScript, ReactJs, Material UI

### CODE REVIEW

**Review by Evavic44 — CHANGES_REQUESTED** [review]
Thanks for the PR @Sachin-chaurasiya Can you please add your portfolio without indenting the lines? 🙂 

Also, there are some conflicts in your PR so see if you can update your branch and push again. If you need any assistance in doing that, do let me know.

**Comment by Sachin-chaurasiya** [comment]
> Thanks for the PR @Sachin-chaurasiya Can you please add your portfolio without indenting the lines? 🙂
> 
> Also, there are some conflicts in your PR so see if you can update your branch and push again. If you need any assistance in doing that, do let me know.

Hey @Evavic44 , I have resolved the conflict and also that indentation is coming automatically.
Let me know if there is any solution to avoid that.
Thanks.

**Comment by Evavic44** [comment]
> > Thanks for the PR @Sachin-chaurasiya Can you please add your portfolio without indenting the lines? 🙂
> > Also, there are some conflicts in your PR so see if you can update your branch and push again. If you need any assistance in doing that, do let me know.
> 
> Hey @Evavic44 , I have resolved the conflict and also that indentation is coming automatically. Let me know if there is any solution to avoid that. Thanks.

If you're on vscode, install formatting toggle. It's an extension that allows you to turn prettier indent on/off. 

formatting

**Comment by Sachin-chaurasiya** [comment]
> > > Thanks for the PR @Sachin-chaurasiya Can you please add your portfolio without indenting the lines? 🙂
> > > Also, there are some conflicts in your PR so see if you can update your branch and push again. If you need any assistance in doing that, do let me know.
> > 
> > 
> > Hey @Evavic44 , I have resolved the conflict and also that indentation is coming automatically. Let me know if there is any solution to avoid that. Thanks.
> 
> If you're on vscode, install formatting toggle. It's an extension that allows you to turn prettier indent on/off.
> 
> formatting

Hey @Evavic44, Thanks for suggesting the quick tool.

**Comment by Sachin-chaurasiya** [comment]
@Evavic44 , Indentation issue is fixed. Please review the PR.

**Review by Evavic44 — APPROVED** [review]
LGTM! Thanks for the PR, @Sachin-chaurasiya 🎖️

**Pull request merged**
