### PR TITLE
Update portfolio.md

### PR DESCRIPTION
**Pull request by Daviddix**
Added my portfolio:)

### Portfolio Author

@Daviddix

### Portfolio Link?

https://nsikandavid.dev

### GitHub Link:
https://github.com/Daviddix/portfolio-ideas

### Tech Stack

ReactJS and CSS

### CODE REVIEW

**Review by israelmitolu — CHANGES_REQUESTED** [review]
Hi @Daviddix 
Can you please compress the image using [compressnow](https://compressnow.com/) or [tinypng](https://tinypng.com/)

Thanks :)

**Comment by Daviddix** [comment]
The image has been compressed, soory it took so much time

**Review by israelmitolu — APPROVED** [review]
LGTM 👍

**Comment by israelmitolu** [comment]
> The image has been compressed, soory it took so much time

It's no problem. Thanks for your contribution!

**Pull request merged**
