### PR TITLE
added my portfolio to the list

### PR DESCRIPTION
**Pull request by jasmeetsinghbhatia**
### Portfolio Author
Jasmeet Singh

### Portfolio Link?
[Portfolio](https://jasmeetsinghbhatia.github.io/resume/)

### GitHub Link:
[Github](https://github.com/jasmeetsinghbhatia/resume)

### Tech Stack
HTML, CSS, JavaScript

### CODE REVIEW

**Review by Evavic44 — APPROVED** [review]
Lol. A fun looking portfolio you have here, @jasmeetsinghbhatia. Thanks for adding it. 😅

**Comment by Evavic44** [comment]
Hey, @jasmeetsinghbhatia can you please check the link to your portfolio? It's throwing an error.

**Comment by jasmeetsinghbhatia** [comment]
> Hey, @jasmeetsinghbhatia can you please check the link to your portfolio? It's throwing an error.

@Evavic44  Oops I missed the https in the url and it picked up your repo as base url and added my portfolio url to end of your repo url . its fixed now waiting for your approval https://github.com/Evavic44/portfolio-ideas/pull/94

**Comment by Evavic44** [comment]
Merged. Thanks. 👍🏾

**Pull request merged**
