### PR TITLE
fix: broken link

### LINKED ISSUE #217: Broken link in README file
On the README, the 30 web developer portfolio to inspire you link is broken. 
Update it with the URL below.

[30 Web Developer Portfolios to Inspire You](https://hashnode.com/post/30-web-developer-portfolios-to-inspire-you-cknfx6wdg069kxws1bjjv8mhw)

Here's a screenshot of the issue link.
issue

### PR DESCRIPTION
**Pull request by vimode**
Fixes #217

### CODE REVIEW

**Review by Evavic44 — APPROVED** [review]
LGTM 👍🏽

**Comment by vimode** [comment]
Thank you @Evavic44 

The same issue exists in portfolio.md
I assumed updating README should also update the same at portfolio.md but it seems like that didn't happen. 

Should I make a new PR to update portfolio.md?

**Comment by Evavic44** [comment]
Hey, @vimode Your changes didn't reflect because we're using an npm command to copy the content of the `README.md` file to `Portfolio.md` whenever a change is made. 

But this will only work when you make the changes from within your editor and not the Github GUI. 

Essentially, running: 

```js
npm run deploy
```
should make the updates, and then another PR can be raised. It's kinda tedious, I know. Which is why it isn't specified on the contributing guidelines. 

Though I'm thinking it may be a good idea to do so for contributors who have the same question.

**Comment by vimode** [comment]
Understood. I will make a PR with the updated deployed version. 

> .... Which is why it isn't specified on the contributing guidelines.
> Though I'm thinking it may be a good idea to do so for contributors who have the same question

The current Contributing guidelines encourages usage of the Github web interface to update the README and add the new portfolios which I assume is to encourage people to easily contribute, especially for beginners. 

So adding the information about updating the deployment might require changing the contributing guidelines completely. As it would not make much sense for the contributor to use the Github web interface to make the changes as they still need to make changes locally.

An alternative solution could be to setup github actions to run `npm run deploy` when the changes are merged?

**Comment by Evavic44** [comment]
> Understood. I will make a PR with the updated deployed version.
> 
> > .... Which is why it isn't specified on the contributing guidelines.
> > Though I'm thinking it may be a good idea to do so for contributors who have the same question
> 
> The current Contributing guidelines encourages usage of the Github web interface to update the README and add the new portfolios which I assume is to encourage people to easily contribute, especially for beginners.
> 
> So adding the information about updating the deployment might require changing the contributing guidelines completely. As it would not make much sense for the contributor to use the Github web interface to make the changes as they still need to make changes locally.
> 
> An alternative solution could be to setup github actions to run `npm run deploy` when the changes are merged?

GitHub actions might be a viable option. If you can raise an issue so we discuss this further. Thanks

**Pull request merged**
