### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sunidhi014**
Added My Portfolio

### Portfolio Author
@sunidhi014 

### Portfolio Link?
https://sunidhi-singh.netlify.app/

### GitHub Link:
https://github.com/sunidhi014

### Tech Stack
HTML, CSS, JavaScript

### CODE REVIEW

**Review by israelmitolu — CHANGES_REQUESTED** [review]
Hi @sunidhi014 
Thanks for adding your portfolio. However, you added your screenshot to the top of the Readme. Kindly remove it, so I can merge your addition. Thanks :)

**Comment by sunidhi014** [comment]
@israelmitolu Done!

**Review by israelmitolu — CHANGES_REQUESTED** [review]
Great. Thank you!
Can you also compress your screenshot? I just noticed it's quite large (1.64mb). We like to keep images lightweight because of the many images in the readme. That way, the site loads faster. 

You can use [tinypng](https://tinypng.com/) or [compressnow](https://compressnow.com/) to compress the size.

**Review by israelmitolu — APPROVED** [review]
LGTM 👍

**Pull request merged**
