### PR TITLE
data: dev-rakeshshaw

### PR DESCRIPTION
**Pull request by dev-rakeshshaw**
Author: PATRICK T.LO | URL: pleaseleaveon.com

### Portfolio Author

PATRICK T.LO

### Portfolio Link?

pleaseleaveon.com

### Tech Stack

HTML5, CSS, JavaScript, jQuery

### CODE REVIEW

**Comment by israelmitolu** [comment]
Thank you for raising a PR, @dev-rakeshshaw. Please align the table lines so that they are consistent with the others.

corrrection (1)

**Review by israelmitolu — CHANGES_REQUESTED** [review]
Thank you for raising a PR, @dev-rakeshshaw. Please align the table lines so that they are consistent with the others.

corrrection (1)

**Review by dev-rakeshshaw — COMMENTED** [review]
Aligned the table lines so that they are consistent with the others.

**Comment by dev-rakeshshaw** [comment]
> Aligned the table lines so that they are consistent with the others.
Aligned the table lines so that they are consistent with the others.

**Review by israelmitolu — COMMENTED** [review]
Great, thank you 👍
I just cleaned it up a bit

**Comment by dev-rakeshshaw** [comment]
> Great, thank you 👍 I just cleaned it up a bit

Thanks Brother.

**Pull request merged**
