### PR TITLE
Add Manuel David Gomez

### PR DESCRIPTION
**Pull request by ManuelDavGomez**
### Portfolio Author

ManuelDavGomez

### Portfolio Link?

https://manueldavgomez.github.io/manueldavidgomez/

### GitHub Link:

https://github.com/ManuelDavGomez/manueldavidgomez

### CODE REVIEW

**Review by Evavic44 — CHANGES_REQUESTED** [review]
test

Can you take a look at this issue, @ManuelDavGomez?

**Comment by ManuelDavGomez** [comment]
what is the problem you have bro?

**Comment by ManuelDavGomez** [comment]
this is the page repo: https://github.com/ManuelDavGomez/manueldavidgomez

and this is the link of the page uploaded to github page: https://manueldavgomez.github.io/manueldavidgomez

Please forgive the inconvenience and problems bro

**Comment by Evavic44** [comment]
> what is the problem you have bro?

The table data does not correspond with the table. In the screenshot I attached above, `Author` and `Screenshot` are on a different table from `link`, `GitHub`, and `Stack`.

**Review by Evavic44 — COMMENTED** [review]
I figured out the issue. I'll fix it and merge later.

**Pull request merged**
