### PR TITLE
Update: dragged to the last 

### PR DESCRIPTION
**Pull request by tam11a**

### CODE REVIEW

**Review by israelmitolu — CHANGES_REQUESTED** [review]
Hi @tam11a 
Thanks for adding your portfolio. However, the screenshot is quite large (~1MB). We have a lot of images in the repo, so we try to make them as low in size as possible. 

Kindly compress it using [compressnow](https://compressnow.com/) or [tinypng](https://tinypng.com/), and then reupload. 

Thanks for your understanding :)

**Comment by tam11a** [comment]
> Hi @tam11a Thanks for adding your portfolio. However, the screenshot is quite large (~1MB). We have a lot of images in the repo, so we try to make them as low in size as possible.
> 
> Kindly compress it using [compressnow](https://compressnow.com/) or [tinypng](https://tinypng.com/), and then reupload.
> 
> Thanks for your understanding :)

Compressed the picture on my repository. Thanks @israelmitolu

**Comment by israelmitolu** [comment]
> > Hi @tam11a Thanks for adding your portfolio. However, the screenshot is quite large (~1MB). We have a lot of images in the repo, so we try to make them as low in size as possible.
> > Kindly compress it using [compressnow](https://compressnow.com/) or [tinypng](https://tinypng.com/), and then reupload.
> > Thanks for your understanding :)
> 
> Compressed the picture on my repository. Thanks @israelmitolu

The picture doesn't exist on your repository anymore. If you need more help, you can follow the steps in the [guideline](https://portfolio-ideas.vercel.app/guide.html#%E2%9A%A1screenshot) 
For now, I'll go ahead to merge your PR and add the picture. 

Thanks again for adding your portfolio!

**Review by israelmitolu — APPROVED** [review]
LGTM 👍

**Pull request merged**
