### PR TITLE
Added Anish De's portfolio

### PR DESCRIPTION
**Pull request by max-programming**
### Portfolio Author
Anish De (@AnishDe12020)

### Portfolio Link?
https://anishde.dev/

### GitHub Link:
https://github.com/AnishDe12020/portfolio

### Tech Stack
Svelte, SvelteKit, Vite, TypeScript, Tailwind CSS

### CODE REVIEW

**Comment by AnishDe12020** [comment]
Hey Usman, really appreciate this! But I am actually almost done with V2 of my portfolio (https://v2.anishde.dev) and if all goes well, it is gonna be on the main domain by tomorrow (or maybe even today). 

Can I let you know as soon as I am done with it (in this issue) and then you can update the tech stack (I am moving to nextjs) and the screenshot or else I can open up a pr for it (whatever works for you)

Just trying to avoid an update pr (or some other conflicting thing) which may be needed as soon as I am done with v2

**Comment by max-programming** [comment]
No issues. I'll make this a draft PR until then. Thanks for letting me know

**Comment by Evavic44** [comment]
Nice portfolio @AnishDe12020. Thanks for adding it @max-programming I'll let you fix the conflicts when you decide to update it. 👍🏽🎉

**Comment by AnishDe12020** [comment]
Hey @max-programming, I am done with v2 and it is on the main domain now, https://anishde.dev

The tech stack is Next.js, TailwindCSS

You can go ahead with the pr

**Comment by max-programming** [comment]
On it!

**Comment by max-programming** [comment]
Ready to merge

**Review by Evavic44 — APPROVED** [review]
LGTM! 👍🏾

**Pull request merged**
