### PR TITLE
Update portfolio.md

### PR DESCRIPTION
**Pull request by priincemuhammad**

### CODE REVIEW

**Review by israelmitolu — CHANGES_REQUESTED** [review]
Awesome portfolio @priincemuhammad 
Kindly move your portfolio to the bottom of the list, so I can merge your PR. Thanks

**Review by israelmitolu — COMMENTED** [review]
Hi @priincemuhammad I have helped compress the image, as it was quite large(~300kb). 

Can you provide the link to your actual portfolio, not your profile? If it's private, let me know :)
You can just comment on it here in this thread. Thanks

**Comment by priincemuhammad** [comment]
> Hi @priincemuhammad I have helped compress the image, as it was quite large(~300kb).
> 
> Can you provide the link to your actual portfolio, not your profile? If it's private, let me know :) You can just comment on it here in this thread. Thanks

**Comment by priincemuhammad** [comment]
> Hi @priincemuhammad I have helped compress the image, as it was quite large(~300kb).
> 
> Can you provide the link to your actual portfolio, not your profile? If it's private, let me know :) You can just comment on it here in this thread. Thanks

https://princemuhammad.pro

please let me know is it ok or not.

**Comment by israelmitolu** [comment]
> https://princemuhammad.pro
> 
> please let me know if is it ok or not.

I mean the link to the code for your portfolio on GitHub. I have gone through your profile, but can't find it, so I'd assume it's private.

**Comment by priincemuhammad** [comment]
oh, I'm sorry it's in private repo.

**Comment by israelmitolu** [comment]
> oh, I'm sorry it's in private repo.

Alright, it's no problem :)
I'll go ahead and add it. Thanks for your contribution 💯

**Review by israelmitolu — APPROVED** [review]

**Pull request merged**
