### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AlpayC**
added portfolio site

### Portfolio Author

 @AlpayC
### Portfolio Link?

 [Website](http://alpaycelik.dev/)

### GitHub Link:

 [What is the github repository?](https://github.com/AlpayC/portfolio_site) 

### Tech Stack

NextJS, TailwindCSS, Typescript,Framer Motion, Swiper, Vercel, NodeMailer

### CODE REVIEW

**Review by israelmitolu — CHANGES_REQUESTED** [review]
Great portfolio @AlpayC !
Kindly compress the screenshot as its quite large (~600kb). You can use [tinypng](https://tinypng.com/) or [compressnow.](https://compressnow.com/) 

Thank you

**Comment by AlpayC** [comment]
hey @israelmitolu , thank you for your hint. I reduced the screenshot with tinypng. Can you check pls ? :)

**Comment by israelmitolu** [comment]
> hey @israelmitolu , thank you for your hint. I reduced the screenshot with tinypng. Can you check pls ? :)

Okay, kindly compress it again and replace it in the Readme.
We try to keep each screenshot under 100kb because of the amount of screenshots in the repo. Thanks for understanding

**Comment by AlpayC** [comment]
> > hey @israelmitolu , thank you for your hint. I reduced the screenshot with tinypng. Can you check pls ? :)
> 
> Okay, kindly compress it again and replace it in the Readme.
> We try to keep each screenshot under 100kb because of the amount of screenshots in the repo. Thanks for understanding 

Okay. Done. The size is now under 100kb. Thanks

**Review by israelmitolu — APPROVED** [review]

**Comment by israelmitolu** [comment]
> > > hey @israelmitolu , thank you for your hint. I reduced the screenshot with tinypng. Can you check pls ? :)
> > 
> > 
> > Okay, kindly compress it again and replace it in the Readme.
> > We try to keep each screenshot under 100kb because of the amount of screenshots in the repo. Thanks for understanding
> 
> Okay. Done. The size is now under 100kb. Thanks

Thank you so much!

**Pull request merged**
