### PR TITLE
Added Hari's portfolio

### PR DESCRIPTION
**Pull request by thughari**

### CODE REVIEW

**Comment by thughari** [comment]
Hi.. is there any action needed from my end?

**Review by israelmitolu — CHANGES_REQUESTED** [review]
Hi @thughari  
Thanks for adding your portfolio. However, the screenshot is a bit large. We have many images in the repo, so we try to make them as small as possible. Ideally less than 150kB.

Kindly compress it using [compressnow](https://compressnow.com/) or [tinypng](https://tinypng.com/), and then reupload. 

Thanks for your understanding :)

**Comment by thughari** [comment]
Hi, I have made my changes, can you please review the new image I have added..

**Review by thughari — COMMENTED** [review]
Hi, I have made my changes, can you please review the new image I have added..

**Comment by thughari** [comment]
Hi, can you please review my change.

**Review by israelmitolu — APPROVED** [review]
Great. Thank you! @thughari

**Pull request merged**
