### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sachind3**
Added my portfolio link

### CODE REVIEW

**Review by israelmitolu — CHANGES_REQUESTED** [review]
Hi @sachind3  
Thanks for adding your portfolio. However, the screenshot is a bit large (~300kB). We have many images in the repo, so we try to make them as small as possible. Ideally less than 150kB.

Kindly compress it using [compressnow](https://compressnow.com/) or [tinypng](https://tinypng.com/), and then reupload. 

Thanks for your understanding :)

**Comment by sachind3** [comment]
Hello, @israelmitolu Thumbnail image is now compressed.
Thanks

**Review by israelmitolu — COMMENTED** [review]
Awesome thanks @sachind3 !

**Comment by sachind3** [comment]
Hello, @israelmitolu Thumbnail image is now compressed. please merge the code

**Pull request merged**
