### PR TITLE
author: Lynn Fisher | url: lynnandtonic.com

### PR DESCRIPTION
**Pull request by dev-rakeshshaw**
data: dev-rakeshshaw

### Portfolio Author

Lynn Fisher

### Portfolio Link?

https://lynnandtonic.com

### GitHub Link:

https://github.com/lynnandtonic

### Tech Stack

HTML5, CSS, JavaScript, SVG, Netlify

### CODE REVIEW

**Review by israelmitolu — COMMENTED** [review]
Hello @dev-rakeshshaw, thanks for raising another PR. 
In case of next time, kindy link to the portfolio repo if its available, rather than their profile. 

I've already made the change. Here's the actual portfolio repo: <https://github.com/lynnandtonic/lynnandtonic.com>

**Review by israelmitolu — CHANGES_REQUESTED** [review]
Also, can you check the portfolio repo again, and add the other technologies used? Thanks!

**Comment by dev-rakeshshaw** [comment]
> Hello @dev-rakeshshaw, thanks for raising another PR. In case of next time, kindy link to the portfolio repo if its available, rather than their profile.
> 
> I've already made the change. Here's the actual portfolio repo: https://github.com/lynnandtonic/lynnandtonic.com

Thanks Brother. I will keep that in mind.

**Comment by dev-rakeshshaw** [comment]
> Also, can you check the portfolio repo again, and add the other technologies used? Thanks!

Ya Sure let me check using wappalyzer

**Comment by dev-rakeshshaw** [comment]
> Also, can you check the portfolio repo again, and add the other technologies used? Thanks!

Done Brother. I have added the other technologies used to build the Portfolio "lynnandtonic.com".
Sorry I was not aware of Wappalyzer so some technologies were left out. It will not happen again.

**Comment by israelmitolu** [comment]
> > Also, can you check the portfolio repo again, and add the other technologies used? Thanks!
> 
> Done Brother. I have added the other technologies used to build the Portfolio "lynnandtonic.com". Sorry I was not aware of Wappalyzer so some technologies were left out. It will not happen again.

Great! It's not a problem at all 👍

**Review by israelmitolu — APPROVED** [review]
Good job @dev-rakeshshaw

**Comment by dev-rakeshshaw** [comment]
> Good job @dev-rakeshshaw

Thanks, Brother.
It`s great to learn in public.

**Pull request merged**
